##############################################################
name: Dominion
author: Pico52
version:
  # The current version of Dominion.
  version: 0.4.0
  # This is for showing the changelog on updates.
  last_run_version: 0.4.0
website: 'http://dev.bukkit.org/bukkit-plugins/dominion/'
##############################################################
# You may only edit anything below this point. #

#ooooooooooooooooooooooo#
#---------Units---------#
#ooooooooooooooooooooooo#
units:
  # The maximum distance a unit can be from a settlement to receive materials.
  pick_up_from_settlement_range: 100
  # The maximum distance a unit can be from a settlement to deposit resources into the settlement.
  drop_off_in_settlement_range: 100
  # The maximum distance a unit can be from an item to pick it up.
  pick_up_range: 10

#ooooooooooooooooooooooo#
#------Settlements------#
#ooooooooooooooooooooooo#
settlements:
  # The base defense that every settlement receives respective to its type.
  defense:
    town: 1500
    city: 3000
    fortress: 2500
  # The percentage of food not within a granary that will decay.
  food_decay: .01
  # The amount of food each peasant will consume.
  food_consumption: .1
  # The percentage of wealth stolen if not within a bank.
  stealing_rate: .01
  # The wealth generated by every employed peasant.
  income_tax: .1

#ooooooooooooooooooooooo#
#--------Biomes---------#
#ooooooooooooooooooooooo#

# Note that all bonuses and penalties are positive values.
biomes:
  plains:
    farm_bonus: .3
    herding_grounds_bonus: .2
    spell_power_penalty: .2
    fishing_penalty: .1
    defense_penalty: .2
  forest:
    woodshop_bonus: .2
    hunting_bonus: .2
    inn_bonus: .2
    food_consumption_penalty: .3
    # Negative attrition damage means it heals/causes less damage to enemy units.
    attrition_damage: -.01
  mountain:
    masonry_bonus: .2
    mining_bonus: .2
    defense_bonus: .2
    wheat_penalty: .4
    trade_penalty: .4
  snow:
    attrition_damage: .01
    # Decomposition bonus is a multiplier, so 0 means no decomposition.
    food_decomposition_bonus: 0
    wheat_penalty: .4
    melon_penalty: .2
    mushroom_penalty: .4
  jungle:
    food_consumption_bonus: .2
    melon_bonus: .3
    unit_food_consumption_penalty: .2
    unit_upkeep_penalty: .2
  swamp:
    mana_capacity_bonus: .3
    mana_regeneration_bonus: .3
    wheat_penalty: .4
    herding_grounds_penalty: .4
  mushroom:
    spell_power_bonus: .3
    mushroom_bonus: .3
    wheat_penalty: .4
    pumpkin_penalty: .2
    melon_penalty: .2
  ocean:
    fishing_bonus: .3
    trade_bonus: .3
    mana_regeneration_penalty: .2
    mining_penalty: .4
  desert:
    training_grounds_bonus: .2
    sandworks_bonus: .3
    farm_penalty: .2
    herding_grounds_penalty: .2
  
#ooooooooooooooooooooooo#
#---------Tasks---------#
#ooooooooooooooooooooooo#
tasks:
  # The time between task updates in seconds.
  production_time: 3600
  unit_time: 600
  spell_time: 600
 
  # Whether to wait until the next hour or minute for the first task to run
  # or to start the task immediately.  True to wait; false if not.
  production_wait_to_next_hour: true
  unit_wait_to_next_minute: true
  spell_wait_to_next_minute: true
 
  # What task ticks are broadcasted to all players on the server.
  broadcast:
    production_tick: true
    unit_tick: false
    spell_tick: false